# Generated by Django 3.1 on 2020-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=200)),
                ('eventdescription', models.TextField()),
                ('eventposter', models.ImageField(blank=True, upload_to='posters')),
                ('eventdate', models.DateTimeField(verbose_name='date of event')),
                ('eventorganizer', models.TextField()),
                ('eventteacher1', models.CharField(max_length=200)),
                ('eventteacher2', models.CharField(max_length=200)),
                ('eventteacher3', models.CharField(blank=True, max_length=200)),
                ('eventconvener1', models.CharField(max_length=200)),
                ('eventconvener2', models.CharField(max_length=200)),
                ('eventdepartment', models.CharField(blank=True, max_length=200)),
                ('eventfinished', models.BooleanField(default=False)),
                ('pubdate', models.DateTimeField(verbose_name='date published')),
                ('eventcomments', models.TextField()),
            ],
        ),
    ]
