# Generated by Django 3.1 on 2020-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventcomments',
            field=models.TextField(blank=True),
        ),
    ]
