# Generated by Django 3.1 on 2020-10-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0002_auto_20200914_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('messageper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depactt.event')),
            ],
        ),
    ]
