# Generated by Django 3.1 on 2020-10-01 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='messagereceiver',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='messagesender',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
