# Generated by Django 3.1 on 2020-10-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0004_auto_20201001_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='messageper',
        ),
    ]
