# Generated by Django 3.1 on 2020-10-02 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0005_remove_messages_messageper'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='messagedate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
