# Generated by Django 3.1 on 2020-10-02 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0006_messages_messagedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='messagesenderid',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
