# Generated by Django 3.1 on 2020-10-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0010_auto_20201002_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Messaging',
        ),
    ]
