# Generated by Django 3.1 on 2020-10-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0011_auto_20201002_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publishedby',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='messaging',
            name='messageseen',
            field=models.BooleanField(default=False),
        ),
    ]
