# Generated by Django 3.1 on 2020-10-09 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0013_auto_20201008_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventfinished',
            new_name='eventcerti',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventcomments',
            new_name='eventreminders',
        ),
        migrations.AddField(
            model_name='event',
            name='eventcontact1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='eventcontact2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='eventfrom',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventlink',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventperks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventpresenter',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventpresenterd',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventregfrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventregto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed')], default='PENDING', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='eventto',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventwhatsapp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateField(verbose_name='date of event'),
        ),
    ]
