# Generated by Django 3.1 on 2020-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0014_auto_20201009_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventconvener2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventfrom',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventorganizer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventpresenter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventpresenterd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventregfrom',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventregto',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventto',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventtype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
