# Generated by Django 3.1 on 2020-10-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0015_auto_20201010_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
