# Generated by Django 3.1 on 2020-10-13 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0016_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('perks', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('whatsapp', models.TextField(blank=True)),
                ('target', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed')], default='PENDING', max_length=200)),
                ('poster', models.ImageField(blank=True, upload_to='posters')),
                ('date', models.DateField(verbose_name='date of event')),
                ('tfrom', models.TimeField(blank=True)),
                ('tto', models.TimeField(blank=True)),
                ('regfrom', models.DateField(blank=True)),
                ('regto', models.DateField(blank=True)),
                ('etype', models.CharField(blank=True, max_length=200)),
                ('presenter', models.CharField(blank=True, max_length=200)),
                ('presenterd', models.CharField(blank=True, max_length=200)),
                ('organizer', models.TextField(blank=True)),
                ('teacher1', models.CharField(max_length=200)),
                ('teacher2', models.CharField(max_length=200)),
                ('teacher3', models.CharField(blank=True, max_length=200)),
                ('convener1', models.CharField(max_length=200)),
                ('convener2', models.CharField(blank=True, max_length=200)),
                ('contact1', models.CharField(blank=True, max_length=200)),
                ('contact2', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('certi', models.BooleanField(default=False)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('reminders', models.TextField(blank=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
