# Generated by Django 3.1 on 2020-10-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0017_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
