# Generated by Django 3.1 on 2020-10-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0018_auto_20201013_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaging',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtitle', models.CharField(blank=True, max_length=200)),
                ('report', models.TextField(blank=True)),
                ('rpubdate', models.DateTimeField(auto_now_add=True)),
                ('erref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.event')),
                ('rby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('cby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ecref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.event')),
            ],
        ),
    ]
