# Generated by Django 3.1 on 2020-10-16 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0021_auto_20201015_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='rpubdate',
        ),
        migrations.AddField(
            model_name='report',
            name='rdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rtime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
