# Generated by Django 3.1 on 2020-10-26 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0022_auto_20201016_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('groupmembers', models.CharField(blank=True, max_length=5)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_first', to=settings.AUTH_USER_MODEL)),
                ('member10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_tenth', to=settings.AUTH_USER_MODEL)),
                ('member11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_eleventh', to=settings.AUTH_USER_MODEL)),
                ('member2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_second', to=settings.AUTH_USER_MODEL)),
                ('member3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_third', to=settings.AUTH_USER_MODEL)),
                ('member4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_fourth', to=settings.AUTH_USER_MODEL)),
                ('member5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_fifth', to=settings.AUTH_USER_MODEL)),
                ('member6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_sixth', to=settings.AUTH_USER_MODEL)),
                ('member7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_seventh', to=settings.AUTH_USER_MODEL)),
                ('member8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_eighth', to=settings.AUTH_USER_MODEL)),
                ('member9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_ninth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.CreateModel(
            name='Preevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed')], default='PENDING', max_length=200)),
                ('poster', models.ImageField(blank=True, upload_to='posters')),
                ('date', models.DateField(blank=True)),
                ('tfrom', models.TimeField(blank=True)),
                ('tto', models.TimeField(blank=True)),
                ('regfrom', models.DateField(blank=True)),
                ('regto', models.DateField(blank=True)),
                ('presenter', models.CharField(blank=True, max_length=200)),
                ('presenterd', models.CharField(blank=True, max_length=200)),
                ('organizer', models.TextField(blank=True)),
                ('budget', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groupmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmessage', models.CharField(max_length=1000)),
                ('gmessagedate', models.DateField(auto_now_add=True)),
                ('gtime', models.TimeField(auto_now_add=True)),
                ('gmessageseen', models.BooleanField(default=False)),
                ('eventref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.event')),
                ('gmessagesender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.grouping')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], default='MRS', max_length=10)),
                ('designation', models.CharField(blank=True, max_length=90)),
                ('contactinfo1', models.CharField(blank=True, max_length=12)),
                ('contactinfo2', models.CharField(blank=True, max_length=12)),
                ('urref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
