# Generated by Django 3.1 on 2020-10-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0023_auto_20201026_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preevent',
            name='poster',
        ),
    ]
