# Generated by Django 3.1 on 2020-10-30 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0025_auto_20201027_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='preevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.preevent'),
        ),
        migrations.AlterField(
            model_name='preevent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed')], default='Pending', max_length=200),
        ),
        migrations.CreateModel(
            name='Precomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('ctime', models.TimeField(auto_now_add=True)),
                ('cby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ecref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.preevent')),
            ],
        ),
    ]
