# Generated by Django 3.1 on 2020-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0026_auto_20201030_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='color',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
