# Generated by Django 3.1 on 2020-11-05 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0029_auto_20201104_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='members_involved', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='group_message_seen', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='preevent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='members_involved_in_preevent', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
