# Generated by Django 3.1 on 2020-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0030_auto_20201105_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='convener1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
