# Generated by Django 3.1 on 2020-11-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0031_auto_20201108_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtitle', models.CharField(blank=True, max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('objectives', models.CharField(blank=True, max_length=400)),
                ('keypoints', models.CharField(blank=True, max_length=400)),
                ('outcomes', models.CharField(blank=True, max_length=200)),
                ('feedback', models.CharField(blank=True, max_length=200)),
                ('rdate', models.DateField(auto_now_add=True)),
                ('rtime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('extras1', models.CharField(blank=True, max_length=400)),
                ('extras2', models.CharField(blank=True, max_length=200)),
                ('extras3', models.CharField(blank=True, max_length=200)),
                ('rdate', models.DateField(auto_now_add=True)),
                ('rtime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='department',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='event',
            name='certion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='registration',
            name='erref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.event'),
        ),
        migrations.AddField(
            model_name='registration',
            name='rby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addreport',
            name='erref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.event'),
        ),
        migrations.AddField(
            model_name='addreport',
            name='rby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
