# Generated by Django 3.1 on 2021-01-05 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depactt', '0032_auto_20201127_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='messagereceiver',
        ),
        migrations.RemoveField(
            model_name='messaging',
            name='messagesender',
        ),
        migrations.AddField(
            model_name='messaging',
            name='messagetag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depactt.messaging'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_of_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messaging',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_sends_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='messagesenderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='just_an_id_of_the_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
