# Generated by Django 3.1 on 2021-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depactt', '0034_auto_20210105_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='poster',
        ),
        migrations.AddField(
            model_name='messaging',
            name='file',
            field=models.FileField(blank=True, upload_to='Files'),
        ),
        migrations.AddField(
            model_name='messaging',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
